# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build,test and deploy Python app to Azure Web App - jsuispassechezjosh

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
        envkey_GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        envkey_PG_DATABASE: ${{ secrets.PG_DATABASE }}
        envkey_PG_HOST: ${{ secrets.PG_HOST }}
        envkey_PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
        envkey_PG_USER: ${{ secrets.PG_USER }}
        file_name: .env

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run tests
      run: python3 tests.py

    - name: Build using AppService-Build
      uses: azure/appservice-build@v2
      with:
        platform: python
        platform-version: '3.8'

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jsuispassechezjosh'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e26d468549d743c9a5ae4d7a55470c9b }}